-- Seed default portal roles
-- Run this in your Supabase SQL Editor to populate the portal_roles table

-- Insert system roles into portal_roles
INSERT INTO portal_roles (id, name, description, permissions, is_default, requires_mfa, status, user_count, created_at, updated_at)
VALUES 
    ('00000000-0000-0000-0000-000000000001', 'Admin User', 'Full portal administration access', 
     '[{"module": "dashboard", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "associations", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "properties", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "units", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "people", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "vendors", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "maintenance", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "inspections", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "documents", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "approvals", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "compliance", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "payments", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "communications", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "reports", "read": true, "write": true, "delete": true, "approve": true},
       {"module": "settings", "read": true, "write": true, "delete": true, "approve": true}]'::jsonb,
     true, true, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000002', 'Portfolio Manager', 'Assigned Portfolio Operations and Management',
     '[{"module": "dashboard", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "associations", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "properties", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "units", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "people", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "vendors", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "maintenance", "read": true, "write": true, "delete": false, "approve": true},
       {"module": "inspections", "read": true, "write": true, "delete": false, "approve": true},
       {"module": "documents", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "approvals", "read": true, "write": false, "delete": false, "approve": true},
       {"module": "compliance", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "payments", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "communications", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "reports", "read": true, "write": true, "delete": false, "approve": false}]'::jsonb,
     true, true, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000003', 'Association Manager', 'Assigned Association Management',
     '[{"module": "dashboard", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "associations", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "properties", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "units", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "people", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "vendors", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "maintenance", "read": true, "write": true, "delete": false, "approve": true},
       {"module": "inspections", "read": true, "write": true, "delete": false, "approve": true},
       {"module": "documents", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "approvals", "read": true, "write": false, "delete": false, "approve": true},
       {"module": "compliance", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "payments", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "communications", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "reports", "read": true, "write": false, "delete": false, "approve": false}]'::jsonb,
     true, true, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000004', 'Property Manager', 'Assigned Property Management',
     '[{"module": "dashboard", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "properties", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "units", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "people", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "vendors", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "maintenance", "read": true, "write": true, "delete": false, "approve": true},
       {"module": "inspections", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "documents", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "payments", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "communications", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "reports", "read": true, "write": false, "delete": false, "approve": false}]'::jsonb,
     true, true, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000005', 'Board Member', 'Assigned Board view and approvals',
     '[{"module": "dashboard", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "associations", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "properties", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "documents", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "reports", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "approvals", "read": true, "write": false, "delete": false, "approve": true}]'::jsonb,
     true, true, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000006', 'Vendor Contractor', 'Assigned Vendor Jobs',
     '[{"module": "dashboard", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "maintenance", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "inspections", "read": true, "write": false, "delete": false, "approve": false}]'::jsonb,
     true, false, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000007', 'Resident', 'Own associated records',
     '[{"module": "dashboard", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "units", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "maintenance", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "documents", "read": true, "write": false, "delete": false, "approve": false}]'::jsonb,
     true, false, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000008', 'Owner', 'Own associated records',
     '[{"module": "dashboard", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "properties", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "units", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "maintenance", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "documents", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "payments", "read": true, "write": false, "delete": false, "approve": false}]'::jsonb,
     true, false, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000009', 'Staff', 'Standard User Access',
     '[{"module": "dashboard", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "associations", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "properties", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "people", "read": true, "write": false, "delete": false, "approve": false}]'::jsonb,
     true, false, 'active', 0, now(), now()),
    
    ('00000000-0000-0000-0000-000000000010', 'Finance User', 'Financial Access Only',
     '[{"module": "dashboard", "read": true, "write": false, "delete": false, "approve": false},
       {"module": "payments", "read": true, "write": true, "delete": false, "approve": false},
       {"module": "reports", "read": true, "write": false, "delete": false, "approve": false}]'::jsonb,
     true, true, 'active', 0, now(), now())
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    permissions = EXCLUDED.permissions,
    is_default = EXCLUDED.is_default,
    requires_mfa = EXCLUDED.requires_mfa,
    status = EXCLUDED.status,
    updated_at = now();

-- Verify seeding
SELECT name, description, is_default, requires_mfa, status, user_count
FROM portal_roles
ORDER BY name;