/**
 * Permission System Configuration
 * Defines all permissions in the system and their matrix for roles
 */

// All possible permissions in the system
export const PERMISSIONS = {
  // Portfolio (multi-association view)
  PORTFOLIO_VIEW: "portfolio.view",
  PORTFOLIO_MANAGE: "portfolio.manage",
  
  // Dashboard (association-level view)
  DASHBOARD_VIEW: "dashboard.view",
  DASHBOARD_MANAGE: "dashboard.manage",
  
  // Associations
  ASSOCIATIONS_VIEW: "associations.view",
  ASSOCIATIONS_CREATE: "associations.create",
  ASSOCIATIONS_EDIT: "associations.edit",
  ASSOCIATIONS_DELETE: "associations.delete",
  
  // Properties
  PROPERTIES_VIEW: "properties.view",
  PROPERTIES_CREATE: "properties.create",
  PROPERTIES_EDIT: "properties.edit",
  PROPERTIES_DELETE: "properties.delete",
  
  // Units
  UNITS_VIEW: "units.view",
  UNITS_CREATE: "units.create",
  UNITS_EDIT: "units.edit",
  UNITS_DELETE: "units.delete",
  
  // People/Contacts
  PEOPLE_VIEW: "people.view",
  PEOPLE_CREATE: "people.create",
  PEOPLE_EDIT: "people.edit",
  PEOPLE_DELETE: "people.delete",
  
  // Vendors
  VENDORS_VIEW: "vendors.view",
  VENDORS_CREATE: "vendors.create",
  VENDORS_EDIT: "vendors.edit",
  VENDORS_DELETE: "vendors.delete",
  
  // Maintenance
  MAINTENANCE_VIEW: "maintenance.view",
  MAINTENANCE_CREATE: "maintenance.create",
  MAINTENANCE_EDIT: "maintenance.edit",
  MAINTENANCE_DELETE: "maintenance.delete",
  MAINTENANCE_APPROVE: "maintenance.approve",
  
  // Inspections
  INSPECTIONS_VIEW: "inspections.view",
  INSPECTIONS_CREATE: "inspections.create",
  INSPECTIONS_EDIT: "inspections.edit",
  INSPECTIONS_DELETE: "inspections.delete",
  
  // Documents
  DOCUMENTS_VIEW: "documents.view",
  DOCUMENTS_CREATE: "documents.create",
  DOCUMENTS_EDIT: "documents.edit",
  DOCUMENTS_DELETE: "documents.delete",
  
  // Approvals
  APPROVALS_VIEW: "approvals.view",
  APPROVALS_CREATE: "approvals.create",
  APPROVALS_VOTE: "approvals.vote",
  APPROVALS_MANAGE: "approvals.manage",
  
  // Compliance
  COMPLIANCE_VIEW: "compliance.view",
  COMPLIANCE_CREATE: "compliance.create",
  COMPLIANCE_EDIT: "compliance.edit",
  COMPLIANCE_DELETE: "compliance.delete",
  
  // Payments/Financial
  PAYMENTS_VIEW: "payments.view",
  PAYMENTS_CREATE: "payments.create",
  PAYMENTS_EDIT: "payments.edit",
  PAYMENTS_DELETE: "payments.delete",
  PAYMENTS_REFUND: "payments.refund",
  
  // Communications
  COMMUNICATIONS_VIEW: "communications.view",
  COMMUNICATIONS_CREATE: "communications.create",
  COMMUNICATIONS_EDIT: "communications.edit",
  COMMUNICATIONS_DELETE: "communications.delete",
  
  // Reports
  REPORTS_VIEW: "reports.view",
  REPORTS_CREATE: "reports.create",
  REPORTS_EXPORT: "reports.export",
  
  // Settings
  SETTINGS_VIEW: "settings.view",
  SETTINGS_EDIT: "settings.edit",
  
  // Admin (Platform Level)
  ADMIN_USERS_MANAGE: "admin.users.manage",
  ADMIN_ROLES_MANAGE: "admin.roles.manage",
  ADMIN_TENANTS_MANAGE: "admin.tenants.manage",
  ADMIN_SYSTEM_SETTINGS: "admin.system.settings",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Permission groups for easier management
export const PERMISSION_GROUPS = {
  PORTFOLIO: [PERMISSIONS.PORTFOLIO_VIEW, PERMISSIONS.PORTFOLIO_MANAGE],
  DASHBOARD: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DASHBOARD_MANAGE],
  ASSOCIATIONS: [PERMISSIONS.ASSOCIATIONS_VIEW, PERMISSIONS.ASSOCIATIONS_CREATE, PERMISSIONS.ASSOCIATIONS_EDIT, PERMISSIONS.ASSOCIATIONS_DELETE],
  PROPERTIES: [PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_CREATE, PERMISSIONS.PROPERTIES_EDIT, PERMISSIONS.PROPERTIES_DELETE],
  UNITS: [PERMISSIONS.UNITS_VIEW, PERMISSIONS.UNITS_CREATE, PERMISSIONS.UNITS_EDIT, PERMISSIONS.UNITS_DELETE],
  PEOPLE: [PERMISSIONS.PEOPLE_VIEW, PERMISSIONS.PEOPLE_CREATE, PERMISSIONS.PEOPLE_EDIT, PERMISSIONS.PEOPLE_DELETE],
  VENDORS: [PERMISSIONS.VENDORS_VIEW, PERMISSIONS.VENDORS_CREATE, PERMISSIONS.VENDORS_EDIT, PERMISSIONS.VENDORS_DELETE],
  MAINTENANCE: [PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_EDIT, PERMISSIONS.MAINTENANCE_DELETE, PERMISSIONS.MAINTENANCE_APPROVE],
  INSPECTIONS: [PERMISSIONS.INSPECTIONS_VIEW, PERMISSIONS.INSPECTIONS_CREATE, PERMISSIONS.INSPECTIONS_EDIT, PERMISSIONS.INSPECTIONS_DELETE],
  DOCUMENTS: [PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_CREATE, PERMISSIONS.DOCUMENTS_EDIT, PERMISSIONS.DOCUMENTS_DELETE],
  APPROVALS: [PERMISSIONS.APPROVALS_VIEW, PERMISSIONS.APPROVALS_CREATE, PERMISSIONS.APPROVALS_VOTE, PERMISSIONS.APPROVALS_MANAGE],
  COMPLIANCE: [PERMISSIONS.COMPLIANCE_VIEW, PERMISSIONS.COMPLIANCE_CREATE, PERMISSIONS.COMPLIANCE_EDIT, PERMISSIONS.COMPLIANCE_DELETE],
  PAYMENTS: [PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_CREATE, PERMISSIONS.PAYMENTS_EDIT, PERMISSIONS.PAYMENTS_DELETE, PERMISSIONS.PAYMENTS_REFUND],
  COMMUNICATIONS: [PERMISSIONS.COMMUNICATIONS_VIEW, PERMISSIONS.COMMUNICATIONS_CREATE, PERMISSIONS.COMMUNICATIONS_EDIT, PERMISSIONS.COMMUNICATIONS_DELETE],
  REPORTS: [PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_CREATE, PERMISSIONS.REPORTS_EXPORT],
  SETTINGS: [PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_EDIT],
  ADMIN: [PERMISSIONS.ADMIN_USERS_MANAGE, PERMISSIONS.ADMIN_ROLES_MANAGE, PERMISSIONS.ADMIN_TENANTS_MANAGE, PERMISSIONS.ADMIN_SYSTEM_SETTINGS],
};

// Default permission matrix for the 10 standard roles
export const DEFAULT_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  admin_user: [
    // Full access to everything
    ...Object.values(PERMISSIONS),
  ],
  portfolio_manager: [
    // Management access but no admin
    PERMISSIONS.PORTFOLIO_VIEW, PERMISSIONS.PORTFOLIO_MANAGE,
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DASHBOARD_MANAGE,
    PERMISSIONS.ASSOCIATIONS_VIEW, PERMISSIONS.ASSOCIATIONS_CREATE, PERMISSIONS.ASSOCIATIONS_EDIT,
    PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_CREATE, PERMISSIONS.PROPERTIES_EDIT,
    PERMISSIONS.UNITS_VIEW, PERMISSIONS.UNITS_CREATE, PERMISSIONS.UNITS_EDIT,
    PERMISSIONS.PEOPLE_VIEW, PERMISSIONS.PEOPLE_CREATE, PERMISSIONS.PEOPLE_EDIT,
    PERMISSIONS.VENDORS_VIEW, PERMISSIONS.VENDORS_CREATE, PERMISSIONS.VENDORS_EDIT,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_EDIT, PERMISSIONS.MAINTENANCE_APPROVE,
    PERMISSIONS.INSPECTIONS_VIEW, PERMISSIONS.INSPECTIONS_CREATE, PERMISSIONS.INSPECTIONS_EDIT,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_CREATE, PERMISSIONS.DOCUMENTS_EDIT,
    PERMISSIONS.APPROVALS_VIEW, PERMISSIONS.APPROVALS_CREATE, PERMISSIONS.APPROVALS_MANAGE,
    PERMISSIONS.COMPLIANCE_VIEW, PERMISSIONS.COMPLIANCE_CREATE, PERMISSIONS.COMPLIANCE_EDIT,
    PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_CREATE, PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.COMMUNICATIONS_VIEW, PERMISSIONS.COMMUNICATIONS_CREATE, PERMISSIONS.COMMUNICATIONS_EDIT,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_CREATE, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_EDIT,
  ],
  association_manager: [
    // Focus on associations and properties
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DASHBOARD_MANAGE,
    PERMISSIONS.ASSOCIATIONS_VIEW, PERMISSIONS.ASSOCIATIONS_CREATE, PERMISSIONS.ASSOCIATIONS_EDIT,
    PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_CREATE, PERMISSIONS.PROPERTIES_EDIT,
    PERMISSIONS.UNITS_VIEW, PERMISSIONS.UNITS_CREATE, PERMISSIONS.UNITS_EDIT,
    PERMISSIONS.PEOPLE_VIEW, PERMISSIONS.PEOPLE_CREATE, PERMISSIONS.PEOPLE_EDIT,
    PERMISSIONS.VENDORS_VIEW, PERMISSIONS.VENDORS_CREATE, PERMISSIONS.VENDORS_EDIT,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_EDIT,
    PERMISSIONS.INSPECTIONS_VIEW, PERMISSIONS.INSPECTIONS_CREATE, PERMISSIONS.INSPECTIONS_EDIT,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_CREATE, PERMISSIONS.DOCUMENTS_EDIT,
    PERMISSIONS.APPROVALS_VIEW, PERMISSIONS.APPROVALS_CREATE,
    PERMISSIONS.COMPLIANCE_VIEW, PERMISSIONS.COMPLIANCE_CREATE, PERMISSIONS.COMPLIANCE_EDIT,
    PERMISSIONS.COMMUNICATIONS_VIEW, PERMISSIONS.COMMUNICATIONS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  property_manager: [
    // Focus on properties, units, maintenance
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DASHBOARD_MANAGE,
    PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_EDIT,
    PERMISSIONS.UNITS_VIEW, PERMISSIONS.UNITS_CREATE, PERMISSIONS.UNITS_EDIT,
    PERMISSIONS.PEOPLE_VIEW, PERMISSIONS.PEOPLE_CREATE, PERMISSIONS.PEOPLE_EDIT,
    PERMISSIONS.VENDORS_VIEW, PERMISSIONS.VENDORS_CREATE,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_EDIT,
    PERMISSIONS.INSPECTIONS_VIEW, PERMISSIONS.INSPECTIONS_CREATE, PERMISSIONS.INSPECTIONS_EDIT,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_CREATE,
    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.COMMUNICATIONS_VIEW, PERMISSIONS.COMMUNICATIONS_CREATE,
  ],
  board_member: [
    // Read-only with voting
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSOCIATIONS_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.UNITS_VIEW,
    PERMISSIONS.PEOPLE_VIEW,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.INSPECTIONS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.APPROVALS_VIEW, PERMISSIONS.APPROVALS_VOTE,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.COMMUNICATIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  vendor_contractor: [
    // Vendor-specific access
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_EDIT, // Can update job status
    PERMISSIONS.DOCUMENTS_VIEW,
  ],
  resident: [
    // Own records only
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.COMMUNICATIONS_VIEW, PERMISSIONS.COMMUNICATIONS_CREATE,
  ],
  owner: [
    // Similar to resident but may have more access
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.UNITS_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.COMMUNICATIONS_VIEW, PERMISSIONS.COMMUNICATIONS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  staff: [
    // Standard operational access
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.UNITS_VIEW,
    PERMISSIONS.PEOPLE_VIEW, PERMISSIONS.PEOPLE_CREATE,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_EDIT,
    PERMISSIONS.INSPECTIONS_VIEW, PERMISSIONS.INSPECTIONS_CREATE,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_CREATE,
    PERMISSIONS.COMMUNICATIONS_VIEW, PERMISSIONS.COMMUNICATIONS_CREATE,
  ],
  finance_user: [
    // Financial access only
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_CREATE, PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.DOCUMENTS_VIEW,
  ],
};

// Helper functions
export function hasPermission(userPermissions: Permission[], requiredPermission: Permission): boolean {
  return userPermissions.includes(requiredPermission);
}

export function hasAnyPermission(userPermissions: Permission[], requiredPermissions: Permission[]): boolean {
  return requiredPermissions.some(perm => userPermissions.includes(perm));
}

export function hasAllPermissions(userPermissions: Permission[], requiredPermissions: Permission[]): boolean {
  return requiredPermissions.every(perm => userPermissions.includes(perm));
}

export function getPermissionsForRole(roleId: string): Permission[] {
  return DEFAULT_ROLE_PERMISSIONS[roleId] || [];
}

export function getModulePermissions(module: keyof typeof PERMISSION_GROUPS): Permission[] {
  return PERMISSION_GROUPS[module] || [];
}
